INSERT INTO Topology (city_name, ID_area) VALUES
	('Agorca', 1),
	('Alano di Piave', 2),
	('Alleghe', 1),
	('Alpago', 2),
	('Arsie', 3),
	('Auronzo di Cadore', 1),
	('Belluno', 2),
	('Borca di Cadore', 1),
	('Borgo Valbelluna', 2),
	('Calalzo di Cadore', 1),
	('Canale d Agordo', 1),
	('Cencenighe Agordino', 1),
	('Cesiomaggiore', 2),
	('Chies d''Alpago', 2),
	('Cibiana di Cadore', 1),
	('Colle Santa Lucia', 1),
	('Comelico Superiore', 1),
	('Cortina d''Ampezzo', 1),
	('Danta di Cadore', 1),
	('Domegge di Cadore', 1),
	('Falcade', 1),
	('Feltre', 2),
	('Fonzaso', 3),
	('Cosaldo', 1),
	('La Valle Agordina', 1),
	('Lamon', 3),
	('Limana', 2),
	('Livinallongo del Col di Lana', 1),
	('Longarone', 1),
	('Lorenzago di Cadore', 1),
	('Lozzo di Cadore', 1),
	('Ospitale di Cadore', 1),
	('Pedavena', 2),
	('Perarolo di Cadore', 1),
	('Pieve di Cadore', 1),
	('Ponte nelle Alpi', 2),
	('Quero Vas', 2),
	('Rivamonte Agordino', 1),
	('Rocca Pietore', 1),
	('San Gregorio nelle Alpi', 2),
	('San Nicolo'' di Comelico', 1),
	('San Pietro di Cadore', 1),
	('San Tomaso Agordino', 1),
	('San Vito di Cadore', 1),
	('Santa Giustina', 2),
	('Santo Stefano di Cadore', 1),
	('Sedico', 2),
	('Selva di Cadore', 1),
	('Seren del Grappa', 2),
	('Sospirolo', 2),
	('Soverzene', 2),
	('Sovramonte', 3),
	('Taibon Agordino', 1),
	('Tambre', 2),
	('Val di Zoldo', 1),
	('Vallada Agordina', 1),
	('Valle di Cadore', 1),
	('Vigo di Cadore', 1),
	('Vodo Cadore', 1),
	('Voltago Agordino', 1),
	('Zoppe'' di Cadore', 1),
	('Abano Terme', 6),
	('Agna', 6),
	('Albignasego', 6),
	('Anguillara Veneta', 6),
	('Arqua'' Petrarca', 6),
	('Arre', 6),
	('Arzergrande', 6),
	('Bagnoli di Sopra', 6),
	('Baone', 6),
	('Barbona', 6),
	('Battaglia Terme', 6),
	('Boara Pisani', 6),
	('Borgo Veneto', 6),
	('Borgoricco', 6),
	('Bovolenta', 6),
	('Brugine', 6),
	('Cadoneghe', 6),
	('Campo San Martino', 6),
	('Campodarsego', 6),
	('Campodoro', 6),
	('Camposampiero', 6),
	('Candiana', 6),
	('Carceri', 6),
	('Carmignano di Brenta', 6),
	('Cartura', 6),
	('Casale di Scodosia', 6),
	('Casalserugo', 6),
	('Castelbaldo', 6),
	('Cervarese Santa Croce', 6),
	('Cinto Euganeo', 6),
	('Cittadella', 6),
	('Codevigo', 6),
	('Conselve', 6),
	('Correzzola', 6),
	('Curtarolo', 6),
	('Due Carrare', 6),
	('Este', 6),
	('Fontaniva', 6),
	('Galliera Veneta', 6),
	('Galzignano Terme', 6),
	('Gazzo|', 6),
	('Grantorto', 6),
	('Granze', 6),
	('Legnaro', 6),
	('Limena', 6),
	('Loreggia', 6),
	('Lozzo Atestino', 6),
	('Masera'' di Padova', 6),
	('Masi', 6),
	('Massanzago', 7),
	('Megliadino San Vitale', 6),
	('Merlara', 6),
	('Mestrino', 6),
	('Monselice', 6),
	('Montagnana', 6),
	('Montegrotto Terme', 6),
	('Noventa Padovana', 6),
	('Ospedaletto Euganeo', 6),
	('Padova', 6),
	('Pernumia', 6),
	('Piacenza d''Adige', 6),
	('Piazzola sul Brenta', 6),
	('Piombino Dese', 7),
	('Piove di Sacco', 6),
	('Polverara', 6),
	('Ponso', 6),
	('Ponte San Nicolo''', 6),
	('Pontelongo', 6),
	('Pozzonovol', 6),
	('Rovolon', 6),
	('Rubano', 6),
	('Saccolongo', 6),
	('San Giorgio delle Pertiche', 6),
	('San Giorgio in Bosco', 6),
	('San Martino di Lupari', 6),
	('San Pietro in Gu''', 6),
	('San Pietro Viminario', 6),
	('Santa Giustina in Colle', 6),
	('Sant''Angelo di Piove di Sacco', 6),
	('Sant''Elena', 6),
	('Sant''Urbano', 6),
	('Saonara', 6),
	('Selvazzano Dentro', 6),
	('Solesino', 6),
	('Stanghella', 6),
	('Teolo', 6),
	('Terrassa Padovana', 6),
	('Tombolo', 6),
	('Torreglia', 6),
	('Trebaseleghe', 7),
	('Tribano', 6),
	('Urbana', 6),
	('Veggiano', 6),
	('Vescovana', 6),
	('Vighizzolo d''Este', 6),
	('Vigodarzere', 6),
	('Vigonza', 6),
	('Villa del Conte', 6),
	('Villa Estense', 6),
	('Villafranca Padovana', 6),
	('Villanova di Camposampiero', 7),
	('Vo''', 6),
	('Adria', 5),
	('Ariano nel Polesine', 5),
	('Arqua'' Polesine', 5),
	('Badia Polesine', 5),
	('Bagnolo di Po', 5),
	('Bergantino', 5),
	('Bosaro', 5),
	('Calto', 5),
	('Canaro', 5),
	('Candal', 5),
	('Castelguglielmo', 5),
	('Castelmassa', 5),
	('Castelnovo Bariano', 5),
	('Ceneselli', 5),
	('Ceregnano', 5),
	('Corbola', 5),
	('Costa di Rovigo', 5),
	('Crespino', 5),
	('Ficarolo', 5),
	('Fiesso Umbertiano', 5),
	('Frassinelle Polesine', 5),
	('Fratta Polesine', 5),
	('Gaiba', 5),
	('Gavello', 5),
	('Giacciano con Baruchella', 5),
	('Guarda Veneta', 5),
	('Lendinara', 5),
	('Loreo', 5),
	('Lusia', 5),
	('Melara', 5),
	('Occhiobello', 5),
	('Papozze', 5),
	('Pettorazza Grimani', 5),
	('Pincara', 5),
	('Polesella', 5),
	('Pontecchio Polesine', 5),
	('Porto Tolle', 5),
	('Porto Viro', 5),
	('Rosolina', 5),
	('Rovigo', 5),
	('Salara', 5),
	('San Bellino', 5),
	('San Martino di Venezze', 5),
	('Stienta', 5),
	('Taglio di Po', 5),
	('Trecenta', 5),
	('Villadose', 5),
	('Villanova del Ghebbo', 5),
	('Villanova Marchesana', 5),
	('Villlamarzana', 5),
	('Altivole', 7),
	('Arcade', 7),
	('Asolo', 3),
	('Borso del Grappa', 3),
	('Breda di Piave', 7),
	('Caerano di San Marco', 2),
	('Cappella Maggiore', 2),
	('Carbonera', 7),
	('Casale sul Sile', 7),
	('Casier', 7),
	('Castelcucco', 3),
	('Castelfranco Veneto', 6),
	('Castello di Godego', 6),
	('Cavaso del Tomba', 2),
	('Cessalto', 8),
	('Chiarano', 8),
	('Cimadolmo', 7),
	('Cison di Valmarino', 2),
	('Codogne''', 8),
	('Colle Umberto', 2),
	('Conegliano', 2),
	('Cordignano', 2),
	('Cornuda', 2),
	('Crocetta del Montello', 2),
	('Farra di Soligo', 2),
	('Follina', 2),
	('Fontanelle', 8),
	('Fonte', 3),
	('Fregona', 2),
	('Gaiarine', 8),
	('Giavera del Montello', 2),
	('Godega di Sant''Urbano', 8),
	('Gorgo al Monticano', 8),
	('Istrana', 7),
	('Loria', 6),
	('Mansue''', 8),
	('Mareno di Piave', 8),
	('Maser', 2),
	('Maserada sul Piave', 7),
	('Meduna di Livenza', 8),
	('Miane', 2),
	('Mogliano Veneto', 7),
	('Monastier di Treviso', 7),
	('Monfumo', 3),
	('Montebelluna', 2),
	('Morgano', 7),
	('Moriago della Battaglia', 2),
	('Motta di Livenza', 8),
	('Nervesa della Battaglia', 2),
	('Oderzo', 8),
	('Ormelle', 7),
	('Orsago', 8),
	('Paese', 7),
	('Pederobba', 2),
	('Pieve del Grappa', 3),
	('Pieve di Soligo', 2),
	('Ponte di Piave', 7),
	('Ponzano Veneto', 7),
	('Portobuffole', 8),
	('Possagno', 2),
	('Povegliano', 7),
	('Preganziol', 7),
	('Quinto di Treviso', 7),
	('Refrontolo', 2),
	('Resana', 6),
	('Revine Lago', 2),
	('Riese Pio X', 6),
	('Roncade', 7),
	('Salgareda', 7),
	('San Biagio di Callalta', 7),
	('San Fior', 2),
	('San Pietro di Feletto', 2),
	('San Polo di Piave', 7),
	('San Vendemiano', 2),
	('San Zenone', 3),
	('Santa Lucia di Piave', 7),
	('Sarmede', 2),
	('Segusino', 2),
	('Sernaglia della Battaglia', 2),
	('Silea', 7),
	('Spresiano', 7),
	('Susegana', 2),
	('Tarzo', 2),
	('Trevignano', 7),
	('Treviso', 7),
	('Valdobbiadene', 2),
	('Vazzola', 8),
	('Vedelago', 7),
	('Vidor', 2),
	('Villorba', 7),
	('Vittorio Veneto', 2),
	('Volpago del Montello', 2),
	('Zenson di Piave', 7),
	('Zero Branco', 7),
	('Annone Veneto', 8),
	('Campagna Lupia', 7),
	('Campolongo Maggiore', 6),
	('Camponogara', 7),
	('Caorle', 8),
	('Cavallino-Treporti', 7),
	('Cavarzere', 6),
	('Ceggia', 8),
	('Chioggia', 6),
	('Cinto Caomaggiore', 8),
	('Cona', 6),
	('Concordia Sagittaria', 8),
	('Dolo', 7),
	('Eraclea', 7),
	('Fiesso d''Artico', 6),
	('Fossalta di Piave', 7),
	('Fossalta di Portogruaro', 8),
	('Fosso''', 6),
	('Gruaro', 8),
	('Jesolo', 7),
	('Marcon', 7),
	('Martellago', 7),
	('Meolo', 7),
	('Mira', 7),
	('Mirano', 7),
	('Musile di Piave', 7),
	('Noale', 7),
	('Noventa di Piave', 7),
	('Pianiga', 7),
	('Portogruaro', 8),
	('Pramaggiore', 8),
	('Quarto d''Altino', 7),
	('Salzano', 7),
	('San Dona'' di Piave', 7),
	('San Michele al Tagliamento', 8),
	('San Stino di Livenza', 8),
	('Santa Maria di Sala', 7),
	('Scorze''', 7),
	('Spinea', 7),
	('Stra', 6),
	('Teglio Veneto', 8),
	('Torre di Mosto', 8),
	('VENEZIA', 7),
	('Vigonovo', 6),
	('Agugliaro', 6),
	('Albettone', 6),
	('Alonte', 6),
	('Altavilla Vicentina', 3),
	('Altissimo', 3),
	('Arcugnano', 6),
	('Arsiero', 3),
	('Arzignano', 3),
	('Asiago', 3),
	('Asigliano Veneto', 6),
	('Barbarano Mossano', 6),
	('Bassano del Grappa', 3),
	('Bolzano Vicentino', 3),
	('Breganze', 3),
	('Brendola', 6),
	('Bressanvido', 3),
	('Brogliano', 3),
	('Caldogno', 3),
	('Caltrano', 3),
	('Calvene', 3),
	('Camisano Vicentino', 6),
	('Campiglia dei Berici', 6),
	('Carre''', 3),
	('Cartigliano', 6),
	('Cassola', 6),
	('Castegnero', 6),
	('Castelgomberto', 3),
	('Chiampo', 3),
	('Chiuppano', 3),
	('Cogollo del Cengio', 3),
	('Colceresa', 3),
	('Cornedo Vicentino', 3),
	('Costabissara', 3),
	('Creazzo', 3),
	('Crespadoro', 3),
	('Dueville', 3),
	('Enego', 3),
	('Fara Vicentino', 3),
	('Foza', 3),
	('Gallio', 3),
	('Gambellara', 3),
	('Gambugliano', 3),
	('Grisignano di Zocco', 6),
	('Grumolo delle Abbadesse', 6),
	('Isola Vicentina', 3),
	('Laghi', 3),
	('Lastebasse', 3),
	('Longare', 3),
	('Lonigo', 6),
	('Lugo di Vicenza', 3),
	('Lusiana Conco', 3),
	('Malo', 3),
	('Marano Vicentino', 3),
	('Marostica', 3),
	('Monte di Malo', 3),
	('Montebello Vicentino', 3),
	('Montecchio Maggiore', 3),
	('Montecchio Precalcino', 3),
	('Montegalda', 6),
	('Montegaldella', 6),
	('Monteviale', 3),
	('Monticello Conte Otto', 3),
	('Montorso Vicentino', 3),
	('Mussolente', 3),
	('Nanto', 6),
	('Nogarole Vicentino', 3),
	('Nove', 3),
	('Noventa Vicentina', 6),
	('Orgiano', 6),
	('Pedemonte', 3),
	('Pianezze', 3),
	('Piovene Rocchette', 3),
	('Poiana Maggiore', 6),
	('Posina', 3),
	('Pove del Grappa', 3),
	('Pozzoleone', 6),
	('Quinto Vicentino', 3),
	('Recoaro Terme', 3),
	('Roana', 3),
	('Romano d''Ezzelino', 3),
	('Rosa''', 6),
	('Rossano Veneto', 6),
	('Rotzo', 3),
	('Salcedo', 3),
	('San Pietro Mussolino', 3),
	('San Vito di Leguzzano', 3),
	('Sandrigo', 3),
	('Santorso', 3),
	('Sarcedo', 3),
	('Sarego', 6),
	('Schiavon', 3),
	('Schio', 3),
	('Solagna', 3),
	('Sossano', 6),
	('Sovizzo', 3),
	('Tezze sul Brenta', 6),
	('Thiene', 3),
	('Tonezza del Cimone', 3),
	('Torrebelvicino', 3),
	('Torri di Quartesolo', 3),
	('Trissino', 3),
	('Affi', 4),
	('Albaredo d''Adige', 6),
	('Angiari', 5),
	('Arcole', 3),
	('Badia Calavena', 4),
	('Bardolino', 4),
	('Belfiore', 4),
	('Bevilacqua', 6),
	('Bonavigo', 6),
	('Boschi Sant Anna', 6),
	('Bosco Chiesanuova', 4),
	('Bovolone', 5),
	('Brentino Belluno', 4),
	('Brenzone sul Garda', 4),
	('Bussolengo', 4),
	('Buttapietra', 5),
	('Caldi ero', 4),
	('Caprino Veronese', 4),
	('Casaleone', 5),
	('Castagnaro', 5),
	('Castel d''Azzano', 5),
	('Castelnuovo del Garda', 4),
	('Cavaion Veronese', 4),
	('Cazzano di Tramigna', 3),
	('Cerea', 5),
	('Cerro Veronese', 4),
	('Cologna Veneta', 6),
	('Colognola ai Colli', 4),
	('Concamarise', 5),
	('Costermano sul Garda', 4),
	('Dolce''', 4),
	('Erbe''', 5),
	('Erbezzo', 4),
	('Ferrara di Monte Baldo', 4),
	('Fumane', 4),
	('Garda', 4),
	('Gazzo Veronese', 5),
	('Grezzana', 4),
	('Illasi', 4),
	('Isola della Scala', 5),
	('Isola Rizza', 5),
	('Lavagno', 4),
	('Lazise', 4),
	('Legnago', 5),
	('Malcesine', 4),
	('Marano di Valpolicella', 4),
	('Mezzane di Sotto', 4),
	('Minerbe', 6),
	('Montecchia di Crosara', 3),
	('Monteforte d''Alpone', 3),
	('Mozzecane', 5),
	('Negrar', 4),
	('Nogara', 5),
	('Nogarole Rocca', 5),
	('Oppeano', 5),
	('Palu''', 5),
	('Pastrengo', 4),
	('Pescantina', 4),
	('Peschiera del Garda', 4),
	('Povegliano Veronese', 5),
	('Pressana', 6),
	('Rivoli Veronese', 4),
	('Ronca''', 3),
	('Ronco all''Adige', 4),
	('Roverchiara', 5),
	('Rovere'' Veronese', 4),
	('Roveredo di Gua''', 6),
	('Salizzole', 5),
	('San Bonifacio', 3),
	('San Giovanni Ilarione', 3),
	('San Giovanni Lupatoto', 5),
	('San Martino Buon Albergo', 4),
	('San Mauro di Saline', 4),
	('San Pietro di Morubio', 5),
	('San Pietro in Cariano', 4),
	('San Zeno di Montagna', 4),
	('Sanguinetto', 5),
	('Sant''Ambrogio di Valpolicella', 4),
	('Sant''Anna d''Alfaedo', 4),
	('Selva di Progno', 4),
	('Soave', 3),
	('Sommacampagna', 4),
	('Sona', 4),
	('Sorga''', 5),
	('Terrazzo', 6),
	('Torri del Benaco', 4),
	('Tregnago', 4),
	('Trevenzuolo', 5),
	('Valeggio sul Mincio', 4),
	('Velo Veronese', 4),
	('Verona', 4),
	('Veronella', 6),
	('Vestenanova', 3),
	('Vigasio', 5),
	('Villa Bartolomea', 5),
	('Villafranca di Verona', 5),
	('Zevio', 4),
	('Zimella', 6);